### ISSUE TITLE
Content to be added down the line

### ISSUE THREAD

**Issue by Gyromancyx** [Gyromancyx/Reclist-Gyroflex-FRA#1]
pour la version française, prière de se diriger plus bas

### Overview

This will be a list of items to be added to this repository. According to feedback changes to this list will be made

### To-Do

- [ ] BGM for recording (so far: 2mora, 14mora, 7mora)
- [x] Extra_CCV (needs further testing, looking for missing combinations)
- [ ] Extra_C-held (needs further testing both in usage as well as phonemizer support)
- [ ] Extra_Fries (needs base oto)
- [ ] Extra_ENG (needs further testing both for new vowels and consonants, as well as checking for aliases and their phonemizer compatibility; also needs to be reworked to include the different extra components present for base French)
- [ ] Extra_ENG_CAN (sub-extension for English based on a community idea; needs testing as well as the work pointed out in Extra_ENG)

### Overview

Ceci est une liste des éléments à ajouter à ce repo. Selon le feedback reçu, des modifications à cette liste sont possibles

### To-Do

- [ ] BGM pour l'enregistrement (à l'instant: 2mora, 14mora. 7mora)
- [x] Extra_CCV (nécessite plus de temps d'essai, vérifier manquants)
- [ ] Extra_C-held (nécessite plus de temps d'essai, au niveau utilisation ainsi que compatibilité phonemizer)
- [ ] Extra_Fries (nécessite un oto de base)
- [ ] Extra_ENG (nécessite plus de temps d'essai pour les nouvelles voyelles et consonnes, ainsi qu'une vérification des aliases et leur compatibilité avec le phonemizer; nécessite également une vérification pour inclure les combinaison présentes dans les listes extra françaises)
- [ ] Extra_ENG_CAN (sous-extension pour la lsite anglaise basé sur un feedback de la communauté; nécessite plus de temps d'essai ainsi que les points inclus sous Extra_ENG)

**Comment by Gyromancyx** [comment]
Extra_CCV went live in its1.0 version; this is the version currently being used for Gyrophare, but because of missing oto configs in other pitches, it is not live on the voicebank repo
SInce I have already been using that for like 90% of the time, I mgiht as well publish it and revise and replace it with a 2.0 once I get to testing that
